---
- name: Set SSH port
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?Port "
    line: "Port {{ ssh_port }}"
    state: present
  become: true
  notify: restart sshd

- name: Disable SSH root login
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?PermitRootLogin "
    line: "PermitRootLogin {{ ssh_permit_root }}"
    state: present
  become: true
  notify: restart sshd

- name: Disable SSH password authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?PasswordAuthentication "
    line: "PasswordAuthentication {{ ssh_password_auth }}"
    state: present
  become: true
  notify: restart sshd
