---
galaxy_info:
  role_name: docker
  author: AM Digital Research Environment
  description: Install and configure Docker Engine and Docker Compose plugin
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
    - name: Debian
      versions:
        - bookworm

dependencies:
  - role: common
